resale_flat:
  outputs:
    dev:
      dataset: resale_flat
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/zanelim/Downloads/personal/secret/meltano-learn-03934027c1d8.json
      location: US
      method: service-account
      priority: interactive
      project: meltano-learn
      threads: 1
      type: bigquery
  target: dev
